/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module test2registers(D_IN, CLK, EN, en2, D_OUT);
  wire _0_;
  wire _1_;
  input CLK;
  input D_IN;
  output D_OUT;
  input EN;
  input en2;
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(D_OUT),
    .A1(D_IN),
    .S(EN),
    .X(_0_)
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(D_OUT),
    .A1(D_IN),
    .S(en2),
    .X(_1_)
  );
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(CLK),
    .D(_1_),
    .Q(D_OUT)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(CLK),
    .D(_0_),
    .Q(D_OUT)
  );
endmodule
