/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

module test4bit(D_IN, CLK, EN, D_OUT);
  wire [3:0] _0_;
  input CLK;
  input [3:0] D_IN;
  output [3:0] D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(D_OUT[1]),
    .A1(D_IN[1]),
    .S(EN),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(D_OUT[2]),
    .A1(D_IN[2]),
    .S(EN),
    .X(_0_[2])
  );
  sky130_fd_sc_hd__mux2_1 _3_ (
    .A0(D_OUT[3]),
    .A1(D_IN[3]),
    .S(EN),
    .X(_0_[3])
  );
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(D_OUT[0]),
    .A1(D_IN[0]),
    .S(EN),
    .X(_0_[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(CLK),
    .D(_0_[0]),
    .Q(D_OUT[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(CLK),
    .D(_0_[1]),
    .Q(D_OUT[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(CLK),
    .D(_0_[2]),
    .Q(D_OUT[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(CLK),
    .D(_0_[3]),
    .Q(D_OUT[3])
  );
endmodule
