/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

module test32bit(D_IN, CLK, EN, D_OUT);
  wire [31:0] _00_;
  input CLK;
  input [31:0] D_IN;
  output [31:0] D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_1 _01_ (
    .A0(D_OUT[8]),
    .A1(D_IN[8]),
    .S(EN),
    .X(_00_[8])
  );
  sky130_fd_sc_hd__mux2_1 _02_ (
    .A0(D_OUT[13]),
    .A1(D_IN[13]),
    .S(EN),
    .X(_00_[13])
  );
  sky130_fd_sc_hd__mux2_1 _03_ (
    .A0(D_OUT[9]),
    .A1(D_IN[9]),
    .S(EN),
    .X(_00_[9])
  );
  sky130_fd_sc_hd__mux2_1 _04_ (
    .A0(D_OUT[6]),
    .A1(D_IN[6]),
    .S(EN),
    .X(_00_[6])
  );
  sky130_fd_sc_hd__mux2_1 _05_ (
    .A0(D_OUT[17]),
    .A1(D_IN[17]),
    .S(EN),
    .X(_00_[17])
  );
  sky130_fd_sc_hd__mux2_1 _06_ (
    .A0(D_OUT[26]),
    .A1(D_IN[26]),
    .S(EN),
    .X(_00_[26])
  );
  sky130_fd_sc_hd__mux2_1 _07_ (
    .A0(D_OUT[22]),
    .A1(D_IN[22]),
    .S(EN),
    .X(_00_[22])
  );
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(D_OUT[27]),
    .A1(D_IN[27]),
    .S(EN),
    .X(_00_[27])
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(D_OUT[11]),
    .A1(D_IN[11]),
    .S(EN),
    .X(_00_[11])
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(D_OUT[10]),
    .A1(D_IN[10]),
    .S(EN),
    .X(_00_[10])
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(D_OUT[21]),
    .A1(D_IN[21]),
    .S(EN),
    .X(_00_[21])
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(D_OUT[16]),
    .A1(D_IN[16]),
    .S(EN),
    .X(_00_[16])
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(D_OUT[12]),
    .A1(D_IN[12]),
    .S(EN),
    .X(_00_[12])
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(D_OUT[25]),
    .A1(D_IN[25]),
    .S(EN),
    .X(_00_[25])
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(D_OUT[31]),
    .A1(D_IN[31]),
    .S(EN),
    .X(_00_[31])
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(D_OUT[24]),
    .A1(D_IN[24]),
    .S(EN),
    .X(_00_[24])
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(D_OUT[0]),
    .A1(D_IN[0]),
    .S(EN),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(D_OUT[3]),
    .A1(D_IN[3]),
    .S(EN),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(D_OUT[7]),
    .A1(D_IN[7]),
    .S(EN),
    .X(_00_[7])
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(D_OUT[4]),
    .A1(D_IN[4]),
    .S(EN),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(D_OUT[5]),
    .A1(D_IN[5]),
    .S(EN),
    .X(_00_[5])
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(D_OUT[2]),
    .A1(D_IN[2]),
    .S(EN),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(D_OUT[1]),
    .A1(D_IN[1]),
    .S(EN),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__mux2_1 _24_ (
    .A0(D_OUT[23]),
    .A1(D_IN[23]),
    .S(EN),
    .X(_00_[23])
  );
  sky130_fd_sc_hd__mux2_1 _25_ (
    .A0(D_OUT[18]),
    .A1(D_IN[18]),
    .S(EN),
    .X(_00_[18])
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(D_OUT[15]),
    .A1(D_IN[15]),
    .S(EN),
    .X(_00_[15])
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(D_OUT[20]),
    .A1(D_IN[20]),
    .S(EN),
    .X(_00_[20])
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(D_OUT[19]),
    .A1(D_IN[19]),
    .S(EN),
    .X(_00_[19])
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(D_OUT[30]),
    .A1(D_IN[30]),
    .S(EN),
    .X(_00_[30])
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(D_OUT[28]),
    .A1(D_IN[28]),
    .S(EN),
    .X(_00_[28])
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(D_OUT[29]),
    .A1(D_IN[29]),
    .S(EN),
    .X(_00_[29])
  );
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(D_OUT[14]),
    .A1(D_IN[14]),
    .S(EN),
    .X(_00_[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(CLK),
    .D(_00_[0]),
    .Q(D_OUT[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(CLK),
    .D(_00_[1]),
    .Q(D_OUT[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(CLK),
    .D(_00_[2]),
    .Q(D_OUT[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(CLK),
    .D(_00_[3]),
    .Q(D_OUT[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(CLK),
    .D(_00_[4]),
    .Q(D_OUT[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(CLK),
    .D(_00_[5]),
    .Q(D_OUT[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(CLK),
    .D(_00_[6]),
    .Q(D_OUT[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(CLK),
    .D(_00_[7]),
    .Q(D_OUT[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(CLK),
    .D(_00_[8]),
    .Q(D_OUT[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(CLK),
    .D(_00_[9]),
    .Q(D_OUT[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(CLK),
    .D(_00_[10]),
    .Q(D_OUT[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(CLK),
    .D(_00_[11]),
    .Q(D_OUT[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(CLK),
    .D(_00_[12]),
    .Q(D_OUT[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(CLK),
    .D(_00_[13]),
    .Q(D_OUT[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(CLK),
    .D(_00_[14]),
    .Q(D_OUT[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(CLK),
    .D(_00_[15]),
    .Q(D_OUT[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(CLK),
    .D(_00_[16]),
    .Q(D_OUT[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(CLK),
    .D(_00_[17]),
    .Q(D_OUT[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(CLK),
    .D(_00_[18]),
    .Q(D_OUT[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(CLK),
    .D(_00_[19]),
    .Q(D_OUT[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(CLK),
    .D(_00_[20]),
    .Q(D_OUT[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(CLK),
    .D(_00_[21]),
    .Q(D_OUT[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(CLK),
    .D(_00_[22]),
    .Q(D_OUT[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(CLK),
    .D(_00_[23]),
    .Q(D_OUT[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(CLK),
    .D(_00_[24]),
    .Q(D_OUT[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _58_ (
    .CLK(CLK),
    .D(_00_[25]),
    .Q(D_OUT[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _59_ (
    .CLK(CLK),
    .D(_00_[26]),
    .Q(D_OUT[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _60_ (
    .CLK(CLK),
    .D(_00_[27]),
    .Q(D_OUT[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _61_ (
    .CLK(CLK),
    .D(_00_[28]),
    .Q(D_OUT[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _62_ (
    .CLK(CLK),
    .D(_00_[29]),
    .Q(D_OUT[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _63_ (
    .CLK(CLK),
    .D(_00_[30]),
    .Q(D_OUT[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _64_ (
    .CLK(CLK),
    .D(_00_[31]),
    .Q(D_OUT[31])
  );
endmodule
