/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 9.0.0 -fPIC -Os) */

module test2bit(D_IN, CLK, EN, D_OUT);
  wire [1:0] _0_;
  input CLK;
  input [1:0] D_IN;
  output [1:0] D_OUT;
  input EN;
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(D_OUT[0]),
    .A1(D_IN[0]),
    .S(EN),
    .X(_0_[0])
  );
  sky130_fd_sc_hd__mux2_1 _2_ (
    .A0(D_OUT[1]),
    .A1(D_IN[1]),
    .S(EN),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(CLK),
    .D(_0_[0]),
    .Q(D_OUT[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(CLK),
    .D(_0_[1]),
    .Q(D_OUT[1])
  );
endmodule
